spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
